/* ========================================
 *  FermentCharge - FermentChargeTables.h
 *
 *  GENERATED by tools/ab/fitshape.py -- do not edit by hand.
 *
 *  Model coefficients we fitted to black-box measurements of a licensed
 *  reference unit. See doc/ferment-charge-design.md for the measurement
 *  method and the raw data. These are our own model parameters; nothing here
 *  was taken from a third-party binary.
 *
 *  Fit quality:
 *    leveller static curve   worst RMS residual 0.30 dB
 *    saturation harmonics    worst RMS residual 2.76 dB
 *    character response      worst RMS residual 0.30 dB
 * ======================================== */

#pragma once

namespace ferment::charge::tables {

// ---- Leveller static curve ------------------------------------------------
// gr(L)   = slope * width * log1p(exp((L - knee)/width))       [reduction, dB]
// gain(L) = plateau - gr(L)
// Indexed by the normalised Compression knob, 0..1.

inline constexpr double kPlateauDb[21] = {
       -2.49136,    -1.93653,    -1.40121,    -0.51981,     0.27942,     1.30027,
        2.48035,     3.51221,     4.58417,     5.19251,     5.99200,     6.87624,
        8.66732,    10.81364,    12.52426,    14.01286,    16.48294,    20.02734,
       24.11351,    30.81974,    37.45030,
};

inline constexpr double kKneeDb[21] = {
       10.00000,     0.39253,    -5.66613,   -10.00224,   -12.82390,   -15.45953,
      -17.80810,   -20.03309,   -22.21124,   -23.93190,   -25.26986,   -26.58097,
      -28.34781,   -30.43528,   -32.54405,   -34.69980,   -38.10897,   -42.87634,
      -48.19163,   -56.34261,   -63.91340,
};

inline constexpr double kSlope[21] = {
        1.09428,     1.20000,     1.02608,     0.93141,     0.91085,     0.90294,
        0.89951,     0.89722,     0.89529,     0.89385,     0.89261,     0.89114,
        0.88879,     0.88543,     0.88102,     0.87521,     0.86285,     0.84492,
        0.83438,     0.83805,     0.85544,
};

inline constexpr double kWidthDb[21] = {
        7.63066,     6.64166,     6.50142,     6.26880,     6.18926,     6.14555,
        6.11964,     6.09764,     6.07589,     6.05914,     6.04470,     6.02561,
        5.99335,     5.94635,     5.88355,     5.79624,     5.59128,     5.24331,
        4.95749,     4.97032,     5.60104,
};

// ---- Ballistics -----------------------------------------------------------
// Time constants in ms, indexed by the normalised knob 0..1.
// Both curves are strongly non-linear, and *ascending = slower*.

inline constexpr double kAttackMs[11] = {
        0.43750,     0.54167,     0.54167,     0.56250,     0.60417,     0.66667,
        0.91667,     1.93750,     4.64583,    11.37500,    21.72917,
};

inline constexpr double kReleaseMs[11] = {
       41.79167,    60.62500,    87.70833,   115.77083,   150.18750,   187.68750,
      225.18750,   275.18750,   349.64583,   410.25000,   465.25000,
};

// ---- Saturation -----------------------------------------------------------
// y = outGain * ( f(drive*x + bias) - f(bias) ),  f = unit-threshold softclip
// with the given knee. Mode order: Mild, Moderate, Hot (matches SatMode).
// Only Mild is asymmetric -- Moderate and Hot measured as pure odd-harmonic
// shapers, with H2 at the numerical floor.

inline constexpr double kSatKnee[3][11] = {
    {
          3.89186,     2.71313,     2.19488,     2.11660,     2.17886,     2.34277,
          2.55072,     2.82741,     3.35277,     4.68680,     7.13635,
    },
    {
          2.42476,     2.22042,     2.11273,     2.09860,     2.14152,     3.99369,
          5.38547,     6.27439,     6.79938,     7.11287,     7.30518,
    },
    {
          1.39966,     1.29227,     1.27085,     1.32816,     1.45843,     1.85485,
          2.41425,     2.54078,     2.08018,     1.53027,     1.31720,
    },
};

inline constexpr double kSatDrive[3][11] = {
    {
          0.27068,     0.39081,     0.50970,     0.99507,     2.28602,     3.87095,
          4.75429,     6.03434,     7.70325,     9.59080,    10.47139,
    },
    {
          0.47051,     0.66313,     1.10287,     1.93625,     3.66235,    10.35755,
         13.01462,    16.01548,    19.75048,    24.43381,    30.29327,
    },
    {
          0.85881,     1.23058,     1.88541,     3.03781,     4.85125,     7.98244,
         12.97288,    25.89346,    72.46375,   256.37475,   500.00000,
    },
};

inline constexpr double kSatOutGain[3][11] = {
    {
          5.02682,     3.81555,     3.20535,     1.79260,     0.85548,     0.52049,
          0.42387,     0.33944,     0.27359,     0.22584,     0.19736,
    },
    {
          2.88506,     2.29659,     1.54914,     0.98333,     0.56233,     0.21828,
          0.18077,     0.15324,     0.13034,     0.11092,     0.09441,
    },
    {
          1.52138,     1.19370,     0.81363,     0.49194,     0.28320,     0.15166,
          0.10591,     0.07789,     0.05950,     0.04616,     0.03593,
    },
};

inline constexpr double kSatBias[3][11] = {
    {
         0.197199,    0.089553,    0.055171,    0.043504,    0.067722,    0.052031,
         0.050565,    0.040349,    0.030730,    0.023255,    0.019233,
    },
    {
         0.000000,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
         0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
    },
    {
         0.000000,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
         0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
    },
};

// ---- Character ------------------------------------------------------------
// Low shelf + mid bell + high shelf. Gains scale linearly with the knob;
// frequencies and Qs are fixed. Mode order: Fat, Warm, Bright (CharMode).

inline constexpr double kCharLowGainDb[3] = {
        5.39312,     5.92804,    -1.32940,
};

inline constexpr double kCharLowFreq[3] = {
          73.91,       57.00,      500.00,
};

inline constexpr double kCharLowQ[3] = {
        0.95558,     0.72180,     1.50000,
};

inline constexpr double kCharMidGainDb[3] = {
       -2.40806,    -3.02456,     1.93422,
};

inline constexpr double kCharMidFreq[3] = {
         843.99,      323.66,     1257.26,
};

inline constexpr double kCharMidQ[3] = {
        0.30000,     1.56527,     3.00000,
};

inline constexpr double kCharHighGainDb[3] = {
        2.17030,    -5.49765,     4.59196,
};

inline constexpr double kCharHighFreq[3] = {
        8422.67,     3747.67,     2443.90,
};

inline constexpr double kCharHighQ[3] = {
        1.17001,     0.70698,     0.69077,
};

} // namespace ferment::charge::tables
