/* ========================================
 *  FermentCharge - FermentChargeProc.cpp
 *
 *  The DSP loop. Model coefficients live in FermentChargeTables.h, which is
 *  generated by tools/ab/fit.py + tools/ab/fitshape.py from black-box
 *  measurements; doc/ferment-charge-design.md records the method and the
 *  residual of every fit.
 *
 *  Three things here are measurement-driven rather than conventional, and
 *  should not be "corrected" without re-reading the design doc:
 *
 *   1. The gain computer is a *leveller*, not a threshold compressor. Its
 *      static curve is a softplus with no identifiable knee, and the
 *      Compression knob sweeps threshold down and makeup up together.
 *   2. The gain cell is perfectly symmetric. The reference's odd-harmonic
 *      signature comes from detector ripple, so it emerges from the
 *      ballistics on its own. Adding a waveshaper here would be wrong.
 *   3. Saturation runs *before* Character. Confirmed by measurement.
 * ======================================== */

#include "FermentCharge.h"
#include "FermentChargeTables.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>

namespace airwinconsolidated::FermentCharge {

namespace tbl = ferment::charge::tables;

static constexpr double kLn10Over20 = 0.11512925464970229;

// --- parameter smoothing ---------------------------------------------------
//
// Every coefficient below is derived from a knob position through a table
// lookup or a filter design, so it is far too costly to redo per sample. The
// block is therefore split into short control blocks: the smoothers advance
// once per control block and the coefficients are rebuilt from the smoothed
// values. Between control blocks the coefficients are held.
//
// 32 samples is 0.67 ms at 48 kHz, so a control block moves a smoother by at
// most 1 - exp(-0.00067/0.015) = 4.4% of its remaining distance to the target.
// Under automation, where the host moves a parameter a little per block, that
// makes the residual staircase two orders of magnitude smaller than the raw
// per-block step.
static constexpr int kControlBlock = 32;

// Smoothing time constant. Long enough that a full-range jump (preset recall)
// glides instead of clicking, short enough that a knob move still tracks the
// hand. Applies to the normalised 0..1 knob, so it is the same wall-clock
// glide for every parameter.
static constexpr double kSmoothSeconds = 0.015;

// A smoother within this distance of its target snaps onto it exactly. Without
// it an exponential never compares equal to its target, so downstream caches
// (updateFilters) would redesign forever after any parameter touch. On a 0..1
// knob this is at most 4e-5 dB of makeup gain.
static constexpr double kParamEpsilon = 1e-6;

// Which parameters are smoothed.
//   - The mode selectors and the sidechain switch are discrete: a smoothed
//     value would sweep through the intervening modes.
//   - Attack and Release set envelope time constants. Stepping one changes how
//     fast the envelope moves, not its value, so the output stays continuous.
static constexpr bool kSmoothed[kNumParameters] = {
    true,   // kParamInput
    true,   // kParamCompression
    false,  // kParamAttack
    false,  // kParamRelease
    true,   // kParamSaturation
    false,  // kParamSatMode
    true,   // kParamCharacter
    false,  // kParamCharMode
    false,  // kParamDetectorHP
    false,  // kParamStereoMode
    false,  // kParamSidechain
    true,   // kParamScGain
    true,   // kParamMix
    true,   // kParamOutput
};

// Extra detector drive per Detector HP setting (Off / 100 Hz / 300 Hz), in dB
// of resulting gain reduction. See updateFilters() for why this exists.
static constexpr double kDetectorMakeupDb[3] = { 0.0, 1.3, 2.8 };
// Representative leveller slope; it sits at 0.89-0.93 across almost the whole
// Compression range (design doc 4), so a single value is accurate enough to
// convert gain-reduction dB into detector dB here.
static constexpr double kLevellerSlopeNominal = 0.89;

// --- helpers ---------------------------------------------------------------

template <int N>
static inline double lookup(const double (&table)[N], double x) noexcept
{
    if (x <= 0.0) return table[0];
    if (x >= 1.0) return table[N - 1];
    const double f = x * (double)(N - 1);
    const int    i = (int)f;
    return table[i] + (table[i + 1] - table[i]) * (f - (double)i);
}

static inline double tauToCoeff(double ms, double sr) noexcept
{
    const double tau = ms * 1e-3;
    return (tau <= 0.0) ? 0.0 : std::exp(-1.0 / (tau * sr));
}

/* One step of an exponential glide. `coeff` is exp(-samples/(tau*sr)), so the
 * trajectory is identical whatever length the host's blocks happen to be. */
static inline double glide(double current, double target, double coeff) noexcept
{
    const double v = target + (current - target) * coeff;
    return (std::fabs(v - target) < kParamEpsilon) ? target : v;
}

static inline double dbToLin(double db) noexcept
{
    return std::exp(db * kLn10Over20);
}

/* Symmetric soft clipper asymptoting to +/-1.
 * `knee` sets how abruptly it bends: ~2 is tanh-soft, ~40 is near hard-clip.
 * Each saturation mode is one fixed knee; the knob drives level into it. */
static inline double softclipUnit(double x, double knee) noexcept
{
    const double a = std::fabs(x);
    if (a < 1e-12) return x;
    return x / std::pow(1.0 + std::pow(a, knee), 1.0 / knee);
}

/* Leveller static curve, in dB.
 * Returns gain *reduction* (>= 0); the plateau/makeup is applied separately
 * so ballistics act only on the dynamic part. */
static inline double grFromLevelDb(double levelDb, double knee, double slope,
                                   double width) noexcept
{
    const double z = (levelDb - knee) / width;
    // log1p(exp(z)) computed stably for large z
    const double sp = (z > 30.0) ? z : std::log1p(std::exp(z));
    return slope * width * sp;
}

// --- filter setup ----------------------------------------------------------

/* Keep a filter's centre frequency below Nyquist.
 * Character's Fat high shelf sits at 8423 Hz, which is above Nyquist at
 * 8 kHz and close to it at 22.05 kHz; the RBJ formulas produce nonsense
 * once tan(pi*f/sr) passes the quarter-rate point. 0.45 leaves a little
 * headroom below the theoretical 0.5 limit. */
static inline double belowNyquist(double freq, double sr) noexcept
{
    const double limit = 0.45 * sr;
    return (freq < limit) ? freq : limit;
}

void FermentCharge::updateFilters(double sr, int hpMode, int charMode,
                                  double charAmt)
{
    const bool srChanged = (sr != cachedSr);

    if (srChanged || hpMode != cachedHp) {
        // Even at "Off" the reference's detector is not flat to DC, so a
        // fixed infrasonic cut is always in circuit.
        //
        // First order, not the 12 dB/oct RBJ low-cut used elsewhere. The
        // reference's gain reduction rolls off gradually from 30 Hz all the
        // way to 1.5 kHz on the 300 Hz setting; a second-order filter reaches
        // its asymptote far too quickly and left the port up to 10 dB adrift
        // at 80 Hz. Measured against the reference in tools/diagnose_charge.py.
        static const double kHpFreq[kNumDetectorHP] = { 20.0, 100.0, 300.0 };
        const double k = std::tan(M_PI * belowNyquist(kHpFreq[hpMode], sr) / sr);
        const double norm = 1.0 / (1.0 + k);
        detHp.setFromCookbook(norm, -norm, 0.0,
                              1.0, (k - 1.0) * norm, 0.0);
        cachedHp = hpMode;
    }
    // Engaging the filter makes the reference compress *harder* on what is
    // left, uniformly across frequency: at 1.5 kHz, where the filter itself is
    // transparent, its gain reduction still deepens from -6.2 to -9.1 dB when
    // the 300 Hz setting is selected. That falls out of its feedback loop —
    // less detector energy, so the loop drives further. This port's gain
    // computer is feed-forward (see header note 1), so the same behaviour has
    // to be supplied explicitly. Values measured with tools/diagnose_charge.py;
    // divided by the leveller slope because detector dB do not map 1:1 to
    // gain-reduction dB.
    detBoost = dbToLin(kDetectorMakeupDb[hpMode] / kLevellerSlopeNominal);

    if (srChanged || charMode != cachedCharMode || charAmt != cachedCharAmt) {
        if (charAmt <= 1e-9) {
            charLow.setIdentity();
            charMid.setIdentity();
            charHigh.setIdentity();
        } else {
            // Gains scale linearly with the knob; frequencies and Qs are
            // fixed per mode. Verified against the reference to <=0.3 dB.
            charLow.setLowShelf(belowNyquist(tbl::kCharLowFreq[charMode], sr),
                                tbl::kCharLowQ[charMode],
                                tbl::kCharLowGainDb[charMode] * charAmt, sr);
            charMid.setBell(belowNyquist(tbl::kCharMidFreq[charMode], sr),
                            tbl::kCharMidQ[charMode],
                            tbl::kCharMidGainDb[charMode] * charAmt, sr);
            charHigh.setHighShelf(belowNyquist(tbl::kCharHighFreq[charMode], sr),
                                  tbl::kCharHighQ[charMode],
                                  tbl::kCharHighGainDb[charMode] * charAmt, sr);
        }
        cachedCharMode = charMode;
        cachedCharAmt = charAmt;
    }

    cachedSr = sr;
}

void FermentCharge::reset() noexcept
{
    envA = envB = 0.0;
    detHp.reset();
    charLow.reset();
    charMid.reset();
    charHigh.reset();
    smoothPrimed = false;
    // The coefficient caches are keyed on live values and self-heal on the next
    // block, so they are left alone; only accumulated state is cleared here.
}

// --- main loop -------------------------------------------------------------

template <typename T>
void FermentCharge::processT(T** inputs, T** outputs, VstInt32 sampleFrames)
{
    T* in1  = inputs[0];
    T* in2  = inputs[1];
    T* sc1  = inputs[2];
    T* sc2  = inputs[3];
    T* out1 = outputs[0];
    T* out2 = outputs[1];

    // A host should always give us a sane rate, but zero or negative would
    // divide by zero when deriving filter coefficients and time constants and
    // spray NaN into the audio stream. Fall back rather than emit garbage.
    // The member, not getSampleRate(): the accessor asserts on a degenerate
    // rate in Debug builds, before this guard ever gets to run.
    double sr = (double)sampleRate;
    if (!(sr > 0.0)) sr = 44100.0;
    const double invTauSr = 1.0 / (kSmoothSeconds * sr);

    if (!smoothPrimed) {
        for (int i = 0; i < kNumParameters; ++i) sm[i] = (double)p[i];
        smoothPrimed = true;
    }

    while (sampleFrames > 0)
    {
        const int frames = (sampleFrames < kControlBlock) ? sampleFrames : kControlBlock;
        sampleFrames -= frames;

        // Advance the smoothers by exactly this control block's length, so the
        // glide is the same however the host chops up the stream.
        {
            const double c = std::exp(-(double)frames * invTauSr);
            for (int i = 0; i < kNumParameters; ++i)
                sm[i] = kSmoothed[i] ? glide(sm[i], (double)p[i], c) : (double)p[i];
        }

        const double inGain   = dbToLin(trimDbFromNorm(sm[kParamInput]));
        const double scGain   = dbToLin(trimDbFromNorm(sm[kParamScGain]));
        const double outGain  = dbToLin(trimDbFromNorm(sm[kParamOutput]));
        const double comp     = sm[kParamCompression];
        const double satAmt   = sm[kParamSaturation];
        const double charAmt  = sm[kParamCharacter];
        const double mix      = sm[kParamMix];
        const double dryMix   = 1.0 - mix;
        const bool   scOn     = sm[kParamSidechain] >= 0.5;

        const int satMode  = modeFromNorm(sm[kParamSatMode], kNumSatModes);
        const int charMode = modeFromNorm(sm[kParamCharMode], kNumCharModes);
        const int hpMode   = modeFromNorm(sm[kParamDetectorHP], kNumDetectorHP);
        const int stMode   = modeFromNorm(sm[kParamStereoMode], kNumStereoModes);

        updateFilters(sr, hpMode, charMode, charAmt);

        // Leveller coefficients for this control block.
        const double plateauDb = lookup(tbl::kPlateauDb, comp);
        const double kneeDb    = lookup(tbl::kKneeDb, comp);
        const double slope     = lookup(tbl::kSlope, comp);
        const double widthDb   = lookup(tbl::kWidthDb, comp);
        const double makeupLin = dbToLin(plateauDb);

        const double atkCoeff = tauToCoeff(lookup(tbl::kAttackMs, sm[kParamAttack]), sr);
        const double relCoeff = tauToCoeff(lookup(tbl::kReleaseMs, sm[kParamRelease]), sr);

        // Saturation: fixed shaper per mode, knob drives level into it. The
        // shaper is never unity — even at the bottom of the knob the fitted
        // drive/outGain pair applies gain — so there is no bypass here.
        const double satKnee  = lookup(tbl::kSatKnee[satMode], satAmt);
        const double satDrive = lookup(tbl::kSatDrive[satMode], satAmt);
        const double satOut   = lookup(tbl::kSatOutGain[satMode], satAmt);
        const double satBias  = lookup(tbl::kSatBias[satMode], satAmt);
        const double satDcOff = softclipUnit(satBias, satKnee);
        const bool   charOn   = charAmt > 1e-9;

        for (int n = frames; n > 0; --n)
        {
            double inL = (double)*in1 * inGain;
            double inR = (double)*in2 * inGain;

            // Dry is captured *before* the denormal guard: the guard's job is to
            // keep the filters and envelopes out of denormal range, and letting it
            // leak into the dry path would stop Mix=0 being a clean bypass.
            const double dryL = inL;
            const double dryR = inR;

            if (std::fabs(inL) < 1.18e-23) inL = fpdL * 1.18e-17;
            if (std::fabs(inR) < 1.18e-23) inR = fpdR * 1.18e-17;

            // --- detector -----------------------------------------------------
            double detL = scOn ? (double)*sc1 * scGain : inL;
            double detR = scOn ? (double)*sc2 * scGain : inR;
            detL = detHp.processL(detL) * detBoost;
            detR = detHp.processR(detR) * detBoost;

            // --- stereo encode ------------------------------------------------
            double a, b, detA, detB;
            if (stMode == MidSide) {
                a = (inL + inR) * 0.5;   b = (inL - inR) * 0.5;
                detA = (detL + detR) * 0.5;  detB = (detL - detR) * 0.5;
            } else {
                a = inL;  b = inR;  detA = detL;  detB = detR;
            }

            // --- level detection ----------------------------------------------
            double lvlA = std::fabs(detA);
            double lvlB = std::fabs(detB);
            if (stMode == StereoLink) {
                lvlA = lvlB = std::max(lvlA, lvlB);
            }

            // --- gain computer + ballistics -------------------------------------
            // Full-wave rectified, no extra smoothing: the ripple this leaves at
            // 2x the input frequency is what produces the reference's odd-harmonic
            // signature. See header note 2.
            const double dbA = 20.0 * std::log10(lvlA + 1e-30);
            const double dbB = 20.0 * std::log10(lvlB + 1e-30);

            const double grA = grFromLevelDb(dbA, kneeDb, slope, widthDb);
            const double grB = grFromLevelDb(dbB, kneeDb, slope, widthDb);

            {
                const double c = (grA > envA) ? atkCoeff : relCoeff;
                envA = c * envA + (1.0 - c) * grA;
            }
            {
                const double c = (grB > envB) ? atkCoeff : relCoeff;
                envB = c * envB + (1.0 - c) * grB;
            }

            a *= makeupLin * dbToLin(-envA);
            b *= makeupLin * dbToLin(-envB);

            // --- stereo decode --------------------------------------------------
            double wetL, wetR;
            if (stMode == MidSide) { wetL = a + b;  wetR = a - b; }
            else                   { wetL = a;      wetR = b;     }

            // --- saturation --
            wetL = satOut * (softclipUnit(satDrive * wetL + satBias, satKnee) - satDcOff);
            wetR = satOut * (softclipUnit(satDrive * wetR + satBias, satKnee) - satDcOff);

            // --- character --------------------------------------------------------
            if (charOn) {
                wetL = charHigh.processL(charMid.processL(charLow.processL(wetL)));
                wetR = charHigh.processR(charMid.processR(charLow.processR(wetR)));
            }

            // --- mix + output ------------------------------------------------------
            double outL = (dryL * dryMix + wetL * mix) * outGain;
            double outR = (dryR * dryMix + wetR * mix) * outGain;

            // --- dither (float path only, Airwindows convention) ---------------------
            if (std::is_same<T, float>::value) {
                int expon;
                std::frexp((float)outL, &expon);
                fpdL ^= fpdL << 13; fpdL ^= fpdL >> 17; fpdL ^= fpdL << 5;
                outL += ((double(fpdL) - (double)0x7fffffff) * 5.5e-36l * std::pow(2.0, expon + 62));
                std::frexp((float)outR, &expon);
                fpdR ^= fpdR << 13; fpdR ^= fpdR >> 17; fpdR ^= fpdR << 5;
                outR += ((double(fpdR) - (double)0x7fffffff) * 5.5e-36l * std::pow(2.0, expon + 62));
            } else {
                fpdL ^= fpdL << 13; fpdL ^= fpdL >> 17; fpdL ^= fpdL << 5;
                fpdR ^= fpdR << 13; fpdR ^= fpdR >> 17; fpdR ^= fpdR << 5;
            }

            *out1 = (T)outL;
            *out2 = (T)outR;

            in1++; in2++; sc1++; sc2++; out1++; out2++;
        }
    }
}

void FermentCharge::processReplacing(float** inputs, float** outputs, VstInt32 sampleFrames)
{
    processT<float>(inputs, outputs, sampleFrames);
}

void FermentCharge::processDoubleReplacing(double** inputs, double** outputs, VstInt32 sampleFrames)
{
    processT<double>(inputs, outputs, sampleFrames);
}

} // namespace airwinconsolidated::FermentCharge
